### ISSUE TITLE
Sample in Chapter 1. Introduction

### ISSUE THREAD

**Issue by angelochen960** [backstopmedia/preact-book-example#7]
Learning PReactjs with this book, still trying some samples in the book, not reach the final project, encounter some issues:

1. Syntax error: SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag, need to wrap the jsx inside a < div >
```
class App extends Component 
{  
	render (props, state) {    
		return (      
			<h1>This is my app</h1>      
			<Paragraph name='Dan' />    
		)  
	}
}
```
2.  Wrong component name, and not working:
```
const Counter = props => <button onClick={this.onClick}>{props.text}</button>
 <Button text='Press me!' onClick={this.handleClick} />
```
Button should have been 'Counter', and the code did not work, have to change to:
```
const Counter = props => <button onClick={props.onClick}>{props.text}</button>
```

**Comment by vutran** [comment]
Hi @angelochen960 ,

You need to wrap your elements (`h1`, and `Paragraph`) into container. This means wrapping it in a `div` or another element.

## Example

```
return (
  <div>
    <h1>This is my app</h1>
    <Paragraph name='Dan' />
  </div>
)
```

**Comment by angelochen960** [comment]
@vutran thanks for the response,  sample code in the book does not wrap it, so for newbie like me, it took a while to figure out, the way I learn is by trying those small samples in the code, very seldom I'll reach the final project in a book, learning from small codes usually enough.

**Comment by vutran** [comment]
Thanks for the feedback! We'll take this into account on future revisions of the book. Please feel free to share more feedback if something stands out.
